### ISSUE TITLE
Empty command sends message to server

### ISSUE THREAD

**Issue by OliverSimpsonTechex** [Simmotipo/baser#13]
Effected version/s: v1.3.4 - v1.3.5, possibly later tbc.
Severity: SL3
Categor(y/ies): New Bug
Description: Just hitting return (CR; empty command) sends empty request to the server. This will result in unnecessary logging.
Steps to replicate: n/a

**Comment by Simmotipo** [comment]
Fixed in 1.6.4; commands of length 0 or consisting of only spaces are ignored and not sent to either remote server or local engine; and don't flag as unknown command
