### ISSUE TITLE
Wildly Excessive Logging

### ISSUE THREAD

**Issue by OliverSimpsonTechex** [Simmotipo/baser#14]
Effected version/s: v1.6.2, possibly more
Severity: SL4
Categor(y/ies): New Bug
Description: NOHUP console is wildly over-populated (thousands upon thousands of >'s spammed). Nohup files hit > 5GB within a week, >10GB easily causing system resource contention
Steps to replicate: n/a

**Comment by OliverSimpsonTechex** [comment]
Possibly linked to https://github.com/Simmotipo/baser/issues/13

**Comment by Simmotipo** [comment]
Work around implemented in 1.6.4 - you can now start baser via "nohup dotnet baser.dll {path} {port} false" to disable local console entirely, preventing erroneous entries to nohup file.

This workaround is yet to be tested, so leaving issue open for now

**Comment by Simmotipo** [comment]
This issue hasn't occurred on test database since update; happy this is resolved in v1.6.4+

Closing this thread for now
